### ISSUE TITLE
Umlaut problem with LDAP authentication

### ISSUE THREAD

**Issue by cgtobi** [frejbow/dudel#4]
When logging in as a user with an umlaut in the (first) name the application crashes with this error message.
> ProgrammingError: (ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. u'UPDATE user SET firstname=? WHERE user.id = ?' ('T\xc3\xb6bias', 1)

[full traceback](http://pastebin.com/3taaYanS)

This is using authentication against LDAP.

**Comment by opatut** [comment]
Done in opatut/dudel 2.0.0 (upstream).
